services:
  flask:
    build: .
    ports:
      - "5000:5000"
    tty: true
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      TZ: "Europe/Vienna"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: codersbay
      POSTGRES_DB: spectaculum
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: